### ISSUE TITLE
CQP abnormal plan

### ISSUE THREAD

**Issue by movingname** [movingname/ddbsim#27]
skipBaselineQuery = true.
network topology exist.
create pairwise comm cost matrix.
defaultSharingCount: 879
extraSharingCount: 0
actualQueryCount is 1000
actualQueryCount is 2000
Abnormal results!!!
java.lang.Exception
	at edu.psu.ist.s2.ITA.utils.Utils.assertion(Utils.java:330)
	at edu.psu.ist.s2.ITA.experiment.MainCQP.runTest(MainCQP.java:190)
	at edu.psu.ist.s2.ITA.experiment.MainCQP.main(MainCQP.java:23)
holder = 1 requesterServ = 1 servNum = 13
S3(P1):R1 S1(P4):R432 to S1(P4) 34708543 peer 2, 34708543
  S3(P1) gets R1(P7) size 29532
  S4(P2):R2 S1(P4):R43 to S1(P4) 34501819 peer 2, 34501819
    S4(P2) gets R2(P2) size 7539
    S5(P9):R3 S7(P5):R4 to S1(P4) 34237954 broker 1, 34237954
      S5(P9) gets R3(P9) size 99954
      S7(P5) gets R4(P5) size 1115132
holder = 1 requesterServ = 1 servNum = 13
S3(P1):R1 S1(P4):R432 to S1(P4) 33726433 peer 2, 33726433
  S3(P1) gets R1(P7) size 29532
  S4(P2):R2 S1(P4):R43 to S1(P4) 34501819 peer 2, 34501819
    S4(P2) gets R2(P2) size 7539
    S5(P9):R3 S7(P5):R4 to S1(P4) 34237954 broker 1, 34237954
      S5(P9) gets R3(P9) size 99954
      S7(P5) gets R4(P5) size 1115132

**Comment by movingname** [comment]
So only the last step calculations are slightly different. Why?

S3(P1):R1 S1(P4):R432 to S1(P4) 34708543 peer 2, 34708543
S3(P1):R1 S1(P4):R432 to S1(P4) 33726433 peer 2, 33726433

**Comment by movingname** [comment]
Another case, same phenomenon. It is quite rare to encounter an abnormal one.

skipBaselineQuery = true.
network topology exist.
create pairwise comm cost matrix.
defaultSharingCount: 902
extraSharingCount: 169
actualQueryCount is 1000
actualQueryCount is 2000
actualQueryCount is 3000
actualQueryCount is 4000
actualQueryCount is 5000
actualQueryCount is 6000
actualQueryCount is 7000
Abnormal results!!!
holder = 1 requesterServ = 1 servNum = 13
S2(P8):R1 S1(P4):R432 to S1(P4) 2069222 semi 2, 2069222
  S2(P8) gets R1(P8) size 36874
  S3(P3):R2 S1(P4):R43 to S1(P4) 1975304 peer 2, 1975304
    S3(P3) gets R2(P3) size 192224
    S7(P5):R3 S7(P5):R4 to S1(P4) 53064 intra 1, 53064
      S7(P5) gets R3(P9) size 74646
      S7(P5) gets R4(P5) size 34575
holder = 1 requesterServ = 1 servNum = 13
S2(P8):R1 S1(P4):R432 to S1(P4) 1590236 semi 2, 1590236
  S2(P8) gets R1(P8) size 36874
  S3(P3):R2 S1(P4):R43 to S1(P4) 1975304 peer 2, 1975304
    S3(P3) gets R2(P3) size 192224
    S7(P5):R3 S7(P5):R4 to S1(P4) 53064 intra 1, 53064
      S7(P5) gets R3(P9) size 74646
      S7(P5) gets R4(P5) size 34575
The query has been written to CQPAbnormalQuery.ser
The coaltion has been written to CQPAbnormalTestPara.ser

**Comment by movingname** [comment]
Related info:

A remote candidate for obtaining 4321 has been included, cost 1590236
S2(P8):R1 S1(P4):R432 to S1(P4) 1590236 semi 2

**Comment by movingname** [comment]
This is the plan from the collaborator:

------------------Query Plan Start------------------
    holder = 1 requesterServ = 1 servNum = 13
    S2(P8):R1 S1(P4):R432 to S1(P4) 1590236 semi 2, 1590236
      S2(P8) gets R1(P8) size 36874
      S5(P9):R2 S1(P4):R43 to S1(P4) 1504410 peer 2, 1504410
        S5(P9) gets R2(P9) size 74646
        S8(P2):R3 S4(P7):R4 to S1(P4) 1205826 peer 2, 1205826
          S8(P2) gets R3(P5) size 34575
          S4(P7) gets R4(P3) size 192224

**Comment by movingname** [comment]
Apparently, step:

    S4(P7) gets R4(P3) size 192224

is wrong, because there is no way S4 can get R4.

**Comment by movingname** [comment]
I have translated the sub query table to parent table, below is the plan from the collaborator. The authorization is all right!

------------------Query Plan Start----------------
holder = 1 requesterServ = 1 servNum = 13
S2(P8):R1 S1(P4):R342 to S1(P4) 1590236 semi 2, 1590236
  S2(P8) gets R1(P8) size 36874
  S5(P9):R3 S1(P4):R42 to S1(P4) 1504410 peer 2, 1504410
    S5(P9) gets R3(P9) size 74646
    S8(P2):R4 S4(P7):R2 to S1(P4) 1205826 peer 2, 1205826
      S8(P2) gets R4(P5) size 34575
      S4(P7) gets R2(P3) size 192224
------------------Query Plan End------------------
A remote candidate for obtaining 4321 has been included, cost 1590236
